
<div class="row">
	
	<div class="col-sm-3">	
		<input type="text" id="find" class="form-control mb-2 border-0" placeholder="Filtro categorias">
		<ul class="list-group" id="box-resultados">
			<?php if($dados_categoria) foreach ($dados_categoria as $row) { ?>
			<li class="list-group-item"><a href="/categoria/<?=$row['url']?>"><?=$row['categoria']?></a></li>
			<?php } ?>						
		</ul>
		<p class="text-center text-muted small mt-2">
			<a href="/categoria/new/" class="btn btn-sm btn-block" data-toggle="modal" data-target="#modal-categoria">Categoria <i class="fa fa-plus-circle"></i></a>			
		</p>
	</div>

	<div class="col-sm-9 links">
		<ul class="list-unstyled">		
			<?php if($dados_links) foreach ($dados_links as $row) { ?>	
			<li class="media mb-2 border-bottom">				
				<div class="media-body ">										
					<span class="badge badge-pill badge-info float-right"><?=$categorias->findID($row['id_categoria'])?></span> 
					<h6 class="mt-0 mb-1 "><?=$row['titulo']?></h6>
					<a href="<?=$row['link']?>" target="_blank"><span class="text-muted d-block"><?=$row['link']?></span></a>					
					<p class="text-muted"><?=$row['descricao']?></p>					
				</div>
			</li>
		<?php } ?>


		</ul>
	</div>

</div>
