		

		</div> <!-- container-fluid -->



<!-- Modal -->
<div class="modal fade" id="modal-novo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<form action="/links/new/" method="POST" >
				<input type="hidden" id="titulo" name="titulo" >
				<div class="modal-header">
					<h5 class="modal-title" id="ModalLabelLink">Novo</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
			
					<div class="form-group">
						<input type="text" name="link" class="form-control title" placeholder="Link" autofocus required>
					</div>
					<div class="row">
						<div class="form-group col-3">							
							<select name="id_categoria" class="form-control" required>
								<?=$form_options?>
							</select>
						</div>  											
						<div class="form-group col-9">
							<input type="text" name="descricao" class="form-control" id="descricao" placeholder="Descrição">
						</div>												
					</div>		

				</div> <!-- body -->
				<div class="modal-footer">					
					<button type="submit" class="btn btn-primary">Inserir</button>
				</div>
			</form>
		</div> <!-- modal-content -->
	</div>
</div>

<!-- Modal Edit -->
<div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<form action="/links/update/" method="POST" id="form-edit">
				<input type="hidden" name="id" >
				<input type="hidden" id="titulo" name="titulo" >
				<div class="modal-header">
					<h5 class="modal-title" id="ModalLabelLink">Editar</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
			
					<div class="form-group">
						<input type="text" name="link" class="form-control title" placeholder="Link" autofocus required>
					</div>
					<div class="row">
						<div class="form-group col-3">							
							<select name="id_categoria" class="form-control" required>
								<?=$form_options?>
							</select>
						</div>  											
						<div class="form-group col-9">
							<input type="text" name="descricao" class="form-control" id="descricao" placeholder="Descrição">
						</div>												
					</div>		

				</div> <!-- body -->
				<div class="modal-footer">					
					<button type="submit" class="btn btn-primary">Inserir</button>
				</div>
			</form>
		</div> <!-- modal-content -->
	</div>
</div>

<!-- Modal Categoria -->
<div class="modal fade" id="modal-categoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<form action="/categoria/new/" method="POST" class="">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<input type="text" name="categoria" class="form-control" placeholder="Categoria" autofocus required>
					</div>    
				</div> <!-- body -->
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</div>
			</form>
		</div> <!-- modal-content -->
	</div>
</div>

<!-- Modal Categoria edit -->
<div class="modal fade" id="modal-categoria-cat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<form action="/categoria/update/" method="POST" id="form-edit-cat">
				<input type="hidden" name="id">
				<div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<input type="text" name="categoria" class="form-control" placeholder="Categoria" required>
					</div>    
				</div> <!-- body -->
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</div>
			</form>
		</div> <!-- modal-content -->
	</div>
</div>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="/node_modules/jquery/dist/jquery.min.js"></script>
		<script src="/node_modules/popper.js/dist/umd/popper.min.js"></script>
		<script src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>					
		<script src="/node_modules/datatables.net/js/jquery.dataTables.js"></script>					
		<script src="/node_modules/datatables.net/js/dataTables.bootstrap4.min.js"></script>					
		<script src="/node_modules/alertify.js/dist/js/alertify.js"></script>					
		<script src="/js/script.js?v=<?=filemtime('js/script.js')?>"></script>
	</body>
</html>