<!DOCTYPE html>
<html lang="pt-br">
	<head>		
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>MyLinks</title>	
		<link rel="apple-touch-icon" sizes="57x57" href="/images/favicon/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/images/favicon/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/images/favicon/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/images/favicon/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/images/favicon/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/images/favicon/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/images/favicon/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/images/favicon/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="/images/favicon/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="/images/favicon/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
		<link rel="manifest" href="/images/favicon/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">		
		<meta name="msapplication-TileImage" content="/images/favicon/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">		

		<link href="/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet">
		<link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">		
		<link href="/node_modules/datatables.net-dt/css/bootstrap.dataTables.css" rel="stylesheet">		
		<link href="/node_modules/alertify.js/dist/css/alertify.css" rel="stylesheet">		
		<link href="/css/style.css?v=<?=filemtime('css/style.css')?>" rel="stylesheet">
	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
			<a class="navbar-brand" href="/"><i class="fa fa-link fa-fw"></i> MyLink</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active"><a class="nav-link" href="/">Home</a></li>					
					<li class="nav-item"><a class="nav-link" href="/links/all">Links</a></li>					
					<li class="nav-item"><a class="nav-link" href="/categoria/all">Categorias</a></li>					
				</ul>
				<form class="form-inline" action="/home/pesquisar/" method="POST">
					<input type="search" name="q" class="form-control mr-sm-2" size="80"  placeholder="Pesquisar" autofocus>					
				</form>
				<ul class="navbar-nav">
					<li class="nav-item"><a href="#" class="btn btn-light btn-block" data-toggle="modal" data-target="#modal-novo">Novo <i class="fa fa-file fa-fw"></i></a></li>
				</ul>
			</div>
		</nav>		
		
		<div class="container-fluid">
		
		